### ISSUE TITLE
Error while running sudo go run . -ul usernames.txt -pl /usr/share/wordlists/rockyou.txt -tl targets.txt -w 10 -p httpdigest

### ISSUE THREAD

**Issue by saddas68** [Rak00n/GoSpray#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x72292b]

goroutine 7 [running]:
main.digestSpray(0xc009c18340?, 0xc004c31080?, {{0xc000099fc0, 0x1, 0x1}, {{0xc0000be9f7, 0xa}, 0x50, {0xc0000be9f0, 0x4}, ...}, ...}, ...)
        /home/kali/GoSpray/digestSpray.go:33 +0x46b
created by main.main
        /home/kali/GoSpray/main.go:140 +0xcc5
exit status 2

**Comment by Rak00n** [comment]
It seems that your tagets are offline or misconfigured. Added little error handling. If the problem persists report me please what target format do yo use.

**Comment by saddas68** [comment]
TY for your support. Now it shows me "HTTP Request failed. Target may be inaccessible or wrong taget format. Get "http://myipaddress/doc/page/login.asp": EOF "
But i can surely access this page, even if i click on it from that console output. Maybe i am just struggling with the right format

**Comment by Rak00n** [comment]
Updated digestspray. It might have happened because of non-closed connections. Could you try it once more?
