### ISSUE TITLE
Why is it printing + on each string?

### ISSUE THREAD

**Issue by useragent23253** [Rak00n/GoSpray#3]
I was testing it like that 
GoSp.exe -p httpbasic -pl pass.txt -tl ip.txt -ul user.txt -rp -ru -w 10
but it's printing "+" or "++" on each string. Also i was testing it with correct username and password but the same thing.

Success: www.cmd5.org:asad23232:asdafswe2

Success: www.cmd5.org:sdgsdgfsd:asdafswe2
+
Success: www.cmd5.org:sdfsdfsdf:asdafswe2
+
Success: www.cmd5.org:asdasdasd:asdafswe2
+
Success: www.cmd5.org:asad23232:asd23dd2wdw
+
Success: www.cmd5.org:sdfsdfsdf:asd23dd2wdw
+
Success: www.cmd5.org:sdgsdgfsd:asd23dd2wdw
+
Success: www.cmd5.org:asdasdasd:asd23dd2wdw

**Comment by Rak00n** [comment]
Hi.
The process if very simple. The tool just check if it receives 401 (unauthorized) and prints "+" (not 401) or "-" (401 received).
In your case you might be checking a resource which is not protected with "basic authentication" and the tool receives many 200 http codes.
Could you write me your target (or just platform, application, language endpoints)?

**Comment by useragent23253** [comment]
I was testing it on my local Qnap Nas

**Comment by Rak00n** [comment]
I've added "-debug" switch for httpbasic. New version has been uploaded. Could you run the tool again and post the output? It just prints http code, http response body and headers for successful attempt.

**Comment by useragent23253** [comment]
I'll check it later bro.
